version: 2
jobs:
 build:
  # Variable expansion in working_directory not supported at this time
  # You will need to modify the code below to reflect your github account/repo setup
  working_directory: /go/src/github.com/nvijayap/invoicer-chapter2
  docker:
   - image: circleci/golang:1.10
  steps:
   - checkout
   - setup_remote_docker

   - run: 
      name: Setup environment
      command: |
       gb="/src/github.com/${CIRCLE_PROJECT_USERNAME}";
       echo "gb: $gb"
       if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then
         dr="securingdevops"
       else
         dr=$DOCKER_USER
       fi
       echo "dr: $dr"
       cat >> $BASH_ENV << EOF
       export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
       export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
       export DOCKER_REPO="$dr"
       EOF
   - run: mkdir -p "${GOPATH_BASE}"
   - run: mkdir -p "${GOPATH_HEAD}/bin"
       
   - run:
      name: Testing application
      command: |
          echo "CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME"
          echo "CIRCLE_PROJECT_REPONAME: CIRCLE_PROJECT_REPONAME"
          go test \
          github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}

   - deploy:
       command: |
         if [ "${CIRCLE_BRANCH}" == "master" ]; then
           echo "Inside if block"
           docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
           [ $? -eq 0 ] && echo "Successful Login"
           go install --ldflags '-extldflags "-static"' \
           github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
           echo "Making bin ..."
           mkdir bin;
           cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
           echo "Building ..."
           docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
           echo "Checking ..."
           docker images --no-trunc | awk '/^app/ {print $3}' | \
             sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
           echo "Pushing ..."
           docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
           echo "... Done ..."
         else
           echo "Branch is not master"
         fi
